### PR TITLE
Site app setting arm template

### PR DESCRIPTION
**Pull request by mikevh**
- Second release of application fails without WebApp AppSetting key MSDEPLOY_RENAME_LOCKED_FILES set to 1. Adding that app setting to the ASP ARM template.
- Seems that AppInsights can no longer be created in Central US, so moved the location of that resource to South Central US.

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
One thing I noticed is that by default there is an app setting already there that is lost.
image

Not sure the best way to handle this.  We could add it to the template as well but then we have to worry about keeping it correct as App Service updates.  I wonder if there is a way to merge the app settings?

**Comment by mikevh** [comment]
Could use set-azurewebsite call in a .ps1 to set the msbuild setting post arm deployment.  Setting that appSetting seems like a workaround to a bug with azure webapps.

Tested the nodejs deployment, no need to set that setting there.  Will test Java next.

**Comment by DarqueWarrior** [comment]
I just promoted the Application Insights location to a parameter that defaults to South Central US and can be passed in as part of the release.  I upped the version to 0.2.0.  I will ping the Azure App Service team to see what we should do about the App Settings they put there. I like your solution of putting in the ARM template much better than the ps1 option so let me see what I can find out.

**Comment by DarqueWarrior** [comment]
Spoke to azure team. We should set it to 6.9.1. They just updated it. I am waiting on if it is needed even if node is not being hosted or not.  Thanks for working on this.

**Comment by mikevh** [comment]
Alrighty, added the node setting to this PR.

**Pull request merged**
